server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    # Настройки для статических файлов
    location ~* \.(jpg|jpeg|png|gif|ico|svg|css|js)$ {
        expires 30d;
        add_header Cache-Control "public, no-transform";
        try_files $uri =404;
    }

    # Запрещаем доступ к .env и другим скрытым файлам
    location ~ /\. {
        deny all;
    }
}