// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc_repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Category struct {
	ID                  int64
	UserID              int64
	Name                string
	Description         *string
	ProgrammingLanguage string
	Color               *string
	Icon                *string
	Status              *string
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
	IsActive            *bool
	IsCommon            *bool
}

type Exercise struct {
	ID                  int64
	UserID              int64
	Title               string
	Description         *string
	CategoryID          int64
	ProgrammingLanguage string
	CodeToRemember      string
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
	IsActive            *bool
	IsCommon            *bool
}

type ExerciseStat struct {
	UserID             int64
	ExerciseID         int64
	TotalAttempts      int32
	SuccessfulAttempts int32
	TotalTypingTime    int64
	TotalTypedChars    int32
	CreatedAt          pgtype.Timestamp
	UpdatedAt          pgtype.Timestamp
}

type User struct {
	UserID             int64
	Name               string
	EvaluationStrategy *string
	MaximumScore       *int32
	IsAdmin            bool
}

type UserAuthProvider struct {
	UserID      int64
	ProviderUid string
	Provider    string
	Name        *string
}
