// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc_repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Category struct {
	ID                  pgtype.UUID
	UserID              int64
	Name                string
	Description         *string
	ProgrammingLanguage string
	Color               *string
	Icon                *string
	Status              *string
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
	IsActive            *bool
}

type Exercise struct {
	ID                  pgtype.UUID
	UserID              int64
	Title               string
	Description         *string
	CategoryID          pgtype.UUID
	Difficulty          string
	ProgrammingLanguage string
	CodeToRemember      string
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
	IsActive            *bool
}

type User struct {
	UserID             int64
	Name               string
	EvaluationStrategy *string
	MaximumScore       *int32
}

type UserAuthProvider struct {
	UserID      int64
	ProviderUid string
	Provider    string
	Name        *string
}
