// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc_repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddUserAuthProviders(ctx context.Context, arg *AddUserAuthProvidersParams) (*UserAuthProvider, error)
	CountCategories(ctx context.Context, userID int64) (int64, error)
	CountCategoriesByLanguage(ctx context.Context, arg *CountCategoriesByLanguageParams) (int64, error)
	CountExercises(ctx context.Context, userID int64) (int64, error)
	CountExercisesByCategory(ctx context.Context, categoryID pgtype.UUID) (int64, error)
	CountExercisesFiltered(ctx context.Context, arg *CountExercisesFilteredParams) (int64, error)
	CreateCategory(ctx context.Context, arg *CreateCategoryParams) (*Category, error)
	CreateExercise(ctx context.Context, arg *CreateExerciseParams) (*Exercise, error)
	CreateUser(ctx context.Context, name string) (int64, error)
	DeleteCategory(ctx context.Context, arg *DeleteCategoryParams) error
	DeleteExercise(ctx context.Context, arg *DeleteExerciseParams) error
	GetCategories(ctx context.Context, arg *GetCategoriesParams) ([]*Category, error)
	GetCategoriesByLanguage(ctx context.Context, arg *GetCategoriesByLanguageParams) ([]*Category, error)
	GetCategory(ctx context.Context, arg *GetCategoryParams) (*Category, error)
	GetExercise(ctx context.Context, arg *GetExerciseParams) (*Exercise, error)
	GetExerciseStat(ctx context.Context, arg *GetExerciseStatParams) (*ExerciseStat, error)
	GetExercises(ctx context.Context, arg *GetExercisesParams) ([]*GetExercisesRow, error)
	GetExercisesFiltered(ctx context.Context, arg *GetExercisesFilteredParams) ([]*GetExercisesFilteredRow, error)
	GetUserAuthProvidersByProviderUid(ctx context.Context, arg *GetUserAuthProvidersByProviderUidParams) (*UserAuthProvider, error)
	GetUserByID(ctx context.Context, userID int64) (*User, error)
	GetUserStats(ctx context.Context, dollar_1 int64) (*GetUserStatsRow, error)
	GetUsersByIDs(ctx context.Context, dollar_1 []int64) ([]*User, error)
	UpdateCategory(ctx context.Context, arg *UpdateCategoryParams) (*Category, error)
	UpdateExercise(ctx context.Context, arg *UpdateExerciseParams) (*Exercise, error)
	UpdateExerciseStat(ctx context.Context, arg *UpdateExerciseStatParams) (*ExerciseStat, error)
	UpdateUserName(ctx context.Context, arg *UpdateUserNameParams) (*User, error)
	UpsertExerciseStat(ctx context.Context, arg *UpsertExerciseStatParams) (*ExerciseStat, error)
}

var _ Querier = (*Queries)(nil)
